CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    hash VARCHAR(64) NOT NULL
);
